In [61]:
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt

In [62]:
data=pd.read_csv('car_data.csv')
inp=pd.read_csv('Input.csv')

In [63]:
data.columns
data

,Id,Model,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar,Price
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,23,10,2002,46986,Diesel,90,1,Blue,...,1,1,0,0,0,1,0,0,0,13500
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,23,10,2002,72937,Diesel,90,1,Silver,...,0,1,0,0,0,1,0,0,0,13750
2,3,ï¿½TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,24,9,2002,41711,Diesel,90,1,Blue,...,0,1,0,0,0,1,0,0,0,13950
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,26,7,2002,48000,Diesel,90,0,Black,...,0,1,0,0,0,1,0,0,0,14950
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,30,3,2002,38500,Diesel,90,0,Black,...,1,1,0,1,0,1,0,0,0,13750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,69,12,1998,20544,Petrol,86,1,Blue,...,1,1,0,1,1,1,0,0,0,7500
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,72,9,1998,19000,Petrol,86,0,Grey,...,0,1,0,0,1,1,0,0,0,10845
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,71,10,1998,17016,Petrol,86,0,Blue,...,0,1,0,0,0,1,0,0,0,8500
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,70,11,1998,16916,Petrol,86,1,Grey,...,0,0,0,0,0,1,0,0,0,7250
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,76,5,1998,1,Petrol,110,0,Green,...,0,1,0,0,0,0,0,0,0,6950

In [64]:
y=data['Price']
data1=data
data1.drop(['Color','Model','Price'],axis=1,inplace=True)
data1['Fuel_Type']=data1['Fuel_Type'].apply(lambda x:1 if (x=='Petrol') else 0)

In [87]:
data1
x_train,x_test,y_train,y_test=train_test_split(data1,y,test_size=0.1,random_state=42)

In [88]:
model=linear_model.LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [89]:
y_pred=model.predict(x_test)
mse=metrics.mean_absolute_error(y_test,y_pred)
mse
mae=metrics.mean_squared_error(y_test,y_pred)
mae

934825.0732793254

In [72]:
output=model.predict(inp)

In [73]:
output

array([19169.98539512])

In [69]:
inp

,Model,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Automatic,cc,...,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar
0,100,30,3,2002,75889,2,90,1,0,2000,...,1,1,1,0,0,0,1,0,0,0